
Resources:
    TransferTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-txn
        AttributeDefinitions:
          - AttributeName: txn_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: txn_id
            KeyType: RANGE
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5