FROM node:18.20-slim as node18_base
WORKDIR /app
COPY package.json .
RUN npm install
FROM node18_base as python_setup
RUN apt-get update
RUN apt-get install python3 python3-pip -y
COPY dev_requirements.txt .
RUN pip3 install --break-system-packages --no-cache-dir --upgrade -r dev_requirements.txt
FROM python_setup as dependencies
COPY serverless.yml .
WORKDIR /app
ENTRYPOINT ["npx","serverless"]
