FROM node:18.20-slim as node18_base
WORKDIR /app
COPY package.json .
RUN npm install
FROM node18_base as python_setup
RUN apt-get update
RUN apt-get install python3 python3-pip python3-venv -y
COPY dev_requirements.txt .
RUN python3 -m venv /app/.venv
SHELL ["/bin/bash", "-c", "source /app/.venv/bin/activate"]
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt
RUN deactivate
FROM python_setup as dependencies
COPY serverless.yml .
RUN source /app/.venv
WORKDIR /app
ENTRYPOINT ["npx","serverless"]
